//
//  textProcessing.swift
//  mindful-moments
//
//  Created by Bryan Murphy on 3/28/24.
//
import Foundation

class textProcessing{
    let stopwords: Set<String> = [
        "a", "was", "of", "and", "the", "in", "to", "is",
            "I", "you", "he", "she", "it", "we", "they", "me", "him", "her", "them",
            "this", "that", "there", "here", "with", "for", "on", "at", "by", "from",
            "as", "or", "but", "not", "if", "when", "where", "how", "why", "which",
            "who", "whom", "whose",
            "have", "has", "had", "do", "does", "did", "will", "would", "can", "could",
            "should", "ought", "must", "might", "may", "into", "out", "up", "down",
            "over", "under", "between", "among", "through", "above", "below", "around",
            "before", "after", "underneath", "beside", "along", "while", "during",
            "against", "within", "without", "across", "beneath", "throughout", "towards",
            "upon", "unto", "am", "are", "being", "been", "being",
            "each", "every", "few", "more", "most", "other", "some", "such", "many",
            "own", "same", "so", "than", "too", "very", "only", "much", "less", "least",
            "just", "ever", "never", "always", "actually", "even", "already", "still",
            "almost", "about", "around", "above", "below", "behind", "besides", "between",
            "beyond", "except", "inside", "outside", "upon", "without", "against", "among",
            "along", "during", "through", "towards", "before", "after", "under", "over",
            "thing", "stuff", "fact", "information", "idea", "thought", "event", "problem",
            "issue", "situation", "case", "point", "aspect", "part", "aspect", "part",
            "element", "factor", "detail", "feature", "example", "instance", "item",
            "matter", "subject", "subject", "subject", "object", "concept", "notion",
            "belief", "opinion", "theory", "hypothesis", "practice", "method", "procedure",
            "process", "system", "strategy", "approach", "technique", "practice", "action",
            "activity", "work", "effort", "attempt", "exercise", "experience", "experiment",
            "trial", "test", "study", "research", "investigation", "analysis", "evaluation",
            "assessment", "review", "examination", "observation", "observation", "observation",
            "observation", "comparison", "contrast", "difference", "similarity", "relation",
            "relationship", "connection", "association", "link", "linkage", "bond", "bridge",
            "transition", "shift", "change", "variation", "difference", "divergence", "variety",
            "range", "scope", "extent", "magnitude", "size", "scale", "dimension", "level",
            "degree", "amount", "quantity", "number", "figure", "total", "whole", "all",
            "every", "any", "none", "nothing", "something", "anything", "everything",
            "everyone", "anyone", "no one", "somebody", "nobody", "something", "nothing",
            "somewhere", "nowhere", "everywhere", "anywhere", "everybody", "anybody", "nobody",
            "someone", "everyone", "anyone", "no one", "thing", "something", "nothing", "anything",
            "everything", "object", "entity", "creature", "being", "item", "article", "commodity",
            "product", "resource", "material", "substance", "matter", "stuff", "thing", "element",
            "component", "part", "piece", "fraction", "bit", "portion", "segment", "section",
            "unit", "module", "ingredient", "aspect", "attribute", "quality", "property", "characteristic",
            "feature", "trait", "mark", "note", "point", "factor", "cause", "reason", "motive",
            "purpose", "intention", "aim", "goal", "objective", "target", "end", "destination",
            "result", "outcome", "consequence", "effect", "impact", "influence", "significance",
            "importance", "relevance", "pertinence", "applicability", "validity", "accuracy",
            "correctness", "truth", "falsity", "error", "mistake", "fallacy", "illusion",
            "misconception", "misinterpretation", "misunderstanding", "confusion", "ambiguity",
            "uncertainty", "doubt", "question", "query", "issue", "problem", "difficulty",
            "challenge", "obstacle", "barrier", "hindrance", "constraint", "limitation",
            "restriction", "boundary", "constraint", "limitation", "restriction", "boundary",
            "condition", "situation", "circumstance", "context", "environment", "setting",
            "surroundings", "surroundings", "surroundings", "surroundings", "surroundings",
            "context", "framework", "perspective", "viewpoint", "standpoint", "angle",
            "position", "stance", "attitude", "approach", "outlook", "belief", "opinion",
            "persuasion", "conviction", "ideology", "philosophy", "doctrine", "principle",
            "value", "standard", "norm", "criteria", "requirement", "expectation", "demand",
            "need", "necessity", "essential", "essential", "essential", "requirement",
            "expectation", "demand", "need", "necessity", "essential", "essential", "essential",
            "priority", "preference", "choice", "decision", "selection", "option", "alternative",
            "possibility", "opportunity", "chance", "prospect", "potential", "potential",
            "capacity", "capability", "ability", "skill", "talent", "aptitude", "gift",
            "endowment", "strength", "advantage", "benefit", "gain", "profit", "reward",
            "advantage"
    ]

    let emotionalDictionary: [String: Set<String>] = [
        "happy": [
                "joy", "happiness", "elation", "euphoria", "bliss", "ecstasy",
                "wonderful", "amazing", "fantastic", "exhilarating", "fulfilled", "content",
                "thankful", "grateful", "blessed", "fortunate",
                "accomplished", "proud", "successful", "victorious",
                "celebration", "party", "outing", "vacation", "adventure",
                "love", "affection", "friendship", "companionship", "caring",
                "hopeful", "optimistic", "excited", "looking forward to",
                "delight", "radiance", "jubilation", "thrill", "enthusiasm",
                "glee", "merriment", "pleasure", "exuberance", "cheer",
                "grin", "beam", "smile", "contentment", "triumph",
                "felicity", "rapture", "uplifted", "serenity", "satisfying",
                "gratifying", "rejoicing", "elated", "delightedness", "cheery",
                "sunny", "bright", "heartening", "gleaming", "joyfulness",
                "lightheartedness", "radiant", "jovial", "delightfulness",
                "thriving", "blissfulness", "enlivened", "gladdened", "jocular",
                "untroubled", "heartfelt", "beatific", "well-being", "giggly", "cheery", "elated", "radiant", "exultant", "euphoric", "sunny", "joyful",
                "blissful", "beaming", "ecstatic", "jovial", "overjoyed", "merry", "gleeful",
                "carefree", "upbeat", "buoyant", "lively", "vibrant", "festive", "exhilarated",
                "thrilled", "contented", "delighted", "grinning", "smiling", "laughing", "chirpy",
                "jaunty", "zestful", "dynamic", "sparkling", "exuberant", "effervescent", "bubbly",
                "spirited", "animated", "enthusiastic", "joyous", "elevated", "jubilant", "jolly",
                "festal", "elation", "cheerful", "happy-go-lucky", "gladsome", "radiating happiness",
                "elated", "on cloud nine", "jumping for joy", "chipper", "bouncy", "joy-filled",
                "jubilant", "blissed out", "full of beans", "as happy as Larry", "high on life",
                "in high spirits", "chuffed", "walking on air", "tickled pink", "giddy", "tickled",
                "cock-a-hoop", "rapturous", "glee", "exultation", "satisfaction", "joyfulness",
                "merriment", "beatitude", "blitheness", "hilarity", "buoyancy", "light-heartedness",
                "jollity", "radiance", "sunshine", "glow", "radiant", "shining", "uplifting",
                "heartwarming", "exhilaration", "uplift", "happily", "satisfying", "rejoicing",
                "satisfied", "chirpy", "lighthearted", "spirited", "sparkling", "effervescent",
                "zestful", "spirited", "animated", "enthusiastic", "joyous", "elevated", "jubilant",
                "jolly", "festal", "exhilarated", "thrilled", "contented", "delighted", "grinning",
                "smiling", "laughing", "chirpy", "jaunty", "zestful", "dynamic", "sparkling",
                "exuberant", "effervescent", "bubbly", "spirited", "animated", "enthusiastic",
                "joyous", "elevated", "jubilant", "jolly", "festal", "elation", "cheerful",
                "happy-go-lucky", "gladsome", "radiating happiness", "elated", "on cloud nine",
                "jumping for joy", "chipper", "bouncy", "joy-filled", "jubilant", "blissed out",
                "full of beans", "as happy as Larry", "high on life", "in high spirits", "chuffed",
                "walking on air", "tickled pink", "giddy", "tickled", "cock-a-hoop", "rapturous",
                "glee", "exultation", "satisfaction", "joyfulness", "merriment", "beatitude",
                "blitheness", "hilarity", "buoyancy", "light-heartedness", "jollity", "radiance",
                "sunshine", "glow", "radiant", "shining", "uplifting", "heartwarming", "exhilaration",
                "uplift", "happily", "satisfying", "rejoicing", "satisfied"],
        "sad": [
                "desolation", "woe", "misery", "despondency", "agony", "desolation",
                "wretchedness", "lamentation", "disconsolate", "forlorn", "dejection",
                "dismay", "bleakness", "desperation", "anguish", "regretful", "lament",
                "sombre", "pensive", "doleful", "melancholy", "grief", "sorrow",
                "despair", "heartache", "hopelessness", "tearful", "mournful",
                "depressed", "unhappy", "crestfallen", "disheartened", "blue",
                "glum", "dismal", "dreary", "downhearted", "heavy-hearted",
                "sullen", "morose", "dispirited", "desolate", "downcast",
                "weary", "tragic", "mourning", "anguished", "despondent", "sorrowful", "grieving", "brokenhearted",
                "tearful", "weepy", "melancholic", "dejected", "downcast", "disappointed",
                "disillusioned", "heartbroken", "bereaved", "bereft", "despairing", "crestfallen",
                "defeated", "deflated", "regretful", "remorseful", "weeping", "sobbing",
                "lamenting", "grieving", "gloomy", "somber", "sullen", "mournful",
                "funereal", "woeful", "pitiful", "troubled", "woebegone", "downtrodden",
                "defeated", "down", "cast down", "despondent", "disconsolate", "disheartened",
                "broken-hearted", "heavyhearted", "sighing", "crying", "weeping", "sad-hearted",
                "low-spirited", "down in the dumps", "in mourning", "in tears", "in sorrow",
                "distressed", "pained", "hurt", "broken", "dispirited", "unconsolable",
                "lachrymose", "blubbering", "dolorous", "blue", "down in the mouth",
                "morbid", "mournful", "plaintive", "wistful", "bitter", "disenchanted",
                "disheartened", "crestfallen", "downhearted", "despairing", "melancholic",
                "miserable", "down", "in the doldrums", "discontented", "displeased",
                "dejected", "discouraged", "forlorn", "gloomy", "glum", "sorrowful",
                "wretched", "downcast", "downhearted", "low", "disappointed", "unhappy",
                "heartbroken", "crestfallen", "disheartened", "miserable", "depressed",
                "despondent", "disconsolate", "grief-stricken", "distraught", "anguished",
                "pained", "suffering", "in despair", "in anguish", "in pain", "in torment",
                "in the depths of despair", "afflicted", "oppressed", "ravaged", "agonized",
                "distressed", "tortured", "wretched", "worrying", "suffering", "tormented",
                "anguishing", "dolorous", "painful", "heart-wrenching", "crushing", "racking",
                "harrowing", "anguished", "tear-stained", "disappointed", "mournful",
                "melancholy", "sorrowful", "wistful", "longing", "yearning", "nostalgic",
                "homesick", "bereft", "grieving", "despairing", "hopeless", "abandoned",
                "desolate", "lonesome", "isolated", "alienated", "forsaken", "alone",
                "rejected", "neglected", "unloved", "unwanted", "misunderstood", "empty",
                "drained", "numb", "broken", "shattered", "crushed", "devastated",
                "ruined", "destroyed", "bereaved", "bereft", "lonely", "solitary"],
        "anger": [
                "rage", "fury", "wrath", "outrage", "resentment", "irritation",
                "hostility", "bitterness", "hatred", "indignation", "frustration",
                "enraged", "mad", "incensed", "annoyed", "infuriated", "aggravated",
                "livid", "raging", "seething", "vexed", "cross", "wrathful", "outraged",
                "agitation", "outburst", "tantrum", "exasperation", "outcry",
                "temper", "angriness", "outrageousness", "ire", "vehemence",
                "storm", "outbreak", "fit", "blowup", "flare-up", "uproar",
                "ferocity", "hysteria", "tantrum", "tantrums", "offense",
                "violent", "outrageously", "incite", "insult", "aggression", "animosity", "antagonism", "belligerence", "choler", "displeasure",
                "enmity", "exasperation", "frenzy", "fume", "grudge", "hate", "hostility",
                "ill will", "impatience", "incitement", "inflammation", "irascibility",
                "malevolence", "mania", "miff", "outrage", "passion", "pique", "provocation",
                "rancor", "resentfulness", "tumult", "turmoil", "vendetta", "violence",
                "vitriol", "wrathfulness", "discontentment", "disgruntlement", "displeasure",
                "dissatisfaction", "irritability", "antipathy", "aversion", "disgust",
                "dislike", "hostility", "resentment", "disapproval", "disdain", "enmity",
                "loathing", "malevolence", "revulsion", "bitterness", "acrimony", "rancor",
                "animus", "hatred", "spite", "malice", "vindictiveness", "acridity",
                "acridness", "acerbity", "acrimony", "asperity", "bitterness", "causticity",
                "mordancy", "sharpness", "trenchancy", "wrath", "wrathfulness", "ire",
                "outrage", "outrageousness", "indignation", "irritation", "aggravation",
                "exasperation", "frustration", "vexation", "annoyance", "irritability",
                "pique", "resentment", "displeasure", "discontent", "dissatisfaction",
                "disgust", "disapprobation", "disapproval", "disinclination", "disliking",
                "antipathy", "aversion", "loathing", "odium", "hostility", "enmity",
                "animosity", "antagonism", "ill will", "bitterness", "rancor", "malevolence",
                "malice", "spite", "venom", "hate", "abhorrence", "abomination", "repugnance",
                "repulsion", "disgust", "hatred", "revulsion", "detestation", "odiousness",
                "execration", "objection", "exception", "disgustfulness", "repugnancy",
                "distaste", "nausea", "aversion", "abhorrence", "repulsion", "horror",
                "loathing", "detestation", "odiousness", "revulsion", "abomination",
                "aversion", "repugnance", "revulsion", "antipathy", "disrelish", "distaste",
                "detestation", "repugnance", "repulsion", "aversion", "loathing", "disfavor",
                "disinclination", "reluctance", "unwillingness", "disgust", "displeasure",
                "antipathy", "aversion", "abhorrence", "detestation", "animosity", "hostility",
                "resentment", "malice", "bitterness", "animus", "acrimony", "rancor",
                "hatred", "repugnance", "loathing", "abomination", "revulsion", "disgust",
                "nausea", "aversion", "horror", "detestation", "abhorrence", "repulsion",
                "loathing", "distaste", "abomination", "repugnance", "dislike", "hatred",
                "hostility", "animosity", "rancor", "bitterness", "resentment", "ill will",
                "antagonism", "animus", "spite", "malice", "venom", "vindictiveness",
                "hatred", "animosity", "rancor", "bitterness", "hostility", "resentment",
                "ill will", "antagonism", "animus", "spite", "malice", "venom",
                "vindictiveness", "hostility", "animosity", "rancor", "bitterness",
                "resentment", "ill will", "antagonism", "animus", "spite", "malice",
                "venom", "vindictiveness", "belligerence", "aggression", "hostility",
                "antagonism", "pugnacity", "combative", "warlike", "quarrelsomeness",
                "argumentativeness", "contentiousness", "bellicosity", "militancy",
                "aggressiveness", "militarism", "confrontational", "hostile", "belligerent",
                "bellicose", "combative", "martial", "quarrelsome", "aggressive",
                "contentious", "antagonistic", "pugnacious", "truculent", "feisty",
                "argumentative", "litigious", "factious", "controversial", "inflammatory",
                "provocative", "incendiary", "inflaming", "instigative", "instigating",
                "stirring", "agitating", "provoking", "inflamatory", "inflamatorily",
                "inflamed", "irritating", "exasperating", "vexing", "annoying", "irritant",
                "bother", "pest", "nuisance", "affront", "indignity", "slight", "insult",
                "offense", "outrage", "provocation", "provoking", "gall", "resentment",
                "bitterness", "annoyance", "exasperation", "irritation", "aggravation"],
        "fear": [
                "terror", "horror", "dread", "fright", "panic", "alarm",
                "anxiety", "apprehension", "unease", "nervousness", "trepidation",
                "phobia", "jitters", "shiver", "shudder", "tremor", "shaking",
                "quaking", "shiver", "shudder", "goosebumps", "petrified", "scared",
                "afraid", "terrified", "panicked", "startled", "spooked", "petrified",
                "hysteria", "paranoia", "claustrophobia", "claustrophobic", "agoraphobia",
                "agoraphobic", "scare", "alarm", "horrified", "apprehensive", "creepy",
                "spine-chilling", "shivery", "nightmarish", "dismay", "consternation", "trepidation", "foreboding", "anguish", "worry",
                "concern", "disquiet", "panic-stricken", "terror-stricken", "terrified",
                "horror-struck", "aghast", "aghast", "aghast", "shocked", "stupefied",
                "appalled", "astounded", "frozen", "paralyzed", "frozen with fear", "paralyzed with fear",
                "petrified", "hyperventilating", "hyperventilation", "sweating", "sweaty palms",
                "shaking", "trembling", "quaking", "quivering", "palpitating", "pounding heart",
                "heart racing", "heart pounding", "heart thumping", "breathless", "shortness of breath",
                "tight chest", "choking sensation", "feeling faint", "weak knees", "rubbery legs",
                "jelly legs", "sinking feeling", "pit in stomach", "butterflies in stomach",
                "knot in stomach", "dizzy", "light-headed", "faint", "woozy", "nauseous",
                "sick to the stomach", "sick", "queasy", "retching", "dry mouth", "cotton mouth",
                "throat tightening", "lump in throat", "mouth going dry", "voice trembling",
                "voice quavering", "voice shaking", "voice breaking", "eyes wide with fear",
                "eyes bulging with fear", "eyes staring in terror", "hair standing on end",
                "sweaty brow", "beads of sweat", "clammy skin", "pale", "pallid", "ashen",
                "sallow", "blood draining from face", "cold sweat", "shivers down spine",
                "hair-raising", "blood-curdling", "bone-chilling", "spine-tingling",
                "hair standing on end", "flesh crawling", "heart-stopping", "jaw-dropping",
                "gut-wrenching", "soul-crushing", "mind-numbing", "terrorizing", "terrifying",
                "horrifying", "panic-inducing", "sudden", "unexpected", "frightening",
                "intense", "overwhelming", "uncontrollable", "paralyzing", "crippling",
                "devastating", "debilitating", "gripping", "consuming", "dominating",
                "constricting", "restrictive", "overpowering", "irrational", "irrational fear",
                "irrational dread", "irrational terror", "unnatural", "supernatural",
                "paranormal", "unnerving", "unsettling", "disturbing", "menacing",
                "threatening", "dreadful", "awful", "dire", "ghastly", "grim",
                "hair-raising", "horrendous", "horrific", "nightmarish", "terrifying",
                "traumatizing", "petrifying", "fearful", "fear-filled", "frightened",
                "scared stiff", "frozen with fright", "paralyzed with fright", "nervous",
                "anxious", "jittery", "tense", "on edge", "panicky", "terrified",
                "horror-stricken", "aghast", "shocked", "stupefied", "appalled", "astonished",
                "frozen", "petrified", "hyperventilating", "sweating", "shaking", "trembling",
                "quaking", "quivering", "palpitating", "breathless", "short of breath",
                "tight-chested", "choking", "feeling faint", "weak-kneed", "rubbery-legged",
                "jelly-legged", "sinking", "pit-of-stomach", "butterflies", "knot", "dizzy",
                "light-headed", "faint", "woozy", "nauseated", "sick", "queasy", "retching",
                "dry-mouthed", "cotton-mouthed", "throat-tightening", "lump-in-throat",
                "voice-trembling", "eye-wide", "hair-raising", "blood-curdling",
                "bone-chilling", "spine-tingling", "hair-standing", "flesh-crawling",
                "jaw-dropping", "gut-wrenching", "soul-crushing", "mind-numbing",
                "terrorizing", "terrifying", "horrifying", "panic-inducing", "sudden",
                "unexpected", "frightening", "intense", "overwhelming", "uncontrollable",
                "paralyzing", "crippling", "devastating", "debilitating", "gripping",
                "consuming", "dominating", "constricting", "restrictive", "overpowering",
                "unnerving", "unsettling", "disturbing", "menacing", "threatening",
                "dreadful", "awful", "dire", "ghastly", "grim", "terrifying", "traumatizing",
                "petrifying", "fearful", "fear-filled", "frightened", "scared stiff",
                "frozen with fright", "paralyzed with fright", "nervous", "anxious"],
        "surprise": [
                "astonishment", "amazement", "shock", "startle", "stun", "dismay",
                "bewilderment", "disbelief", "stagger", "startlement", "awe", "wonder",
                "disconcert", "flabbergast", "confound", "nonplussed", "unsettled",
                "jolt", "jarring", "astound", "dumbfounded", "stupefy", "speechless",
                "thunderstruck", "overwhelmed", "taken aback", "caught off guard",
                "knocked for a loop", "open-mouthed", "wide-eyed", "jaw-dropping",
                "eye-popping", "mind-blowing", "mind-boggling", "flummox", "shocked",
                "surprised", "astonished", "amazed", "stunned", "confused", "baffled",
                "startled", "floored", "startling", "astonishing", "astounding", "mind-blowing", "mind-boggling",
                "jaw-dropping", "eye-opening", "eye-popping", "unexpected", "unanticipated",
                "sudden", "abrupt", "unexpectedly", "abruptly", "aback", "unexpectedly",
                "unexpected", "unforeseen", "unpredicted", "unlooked-for", "unpredicted",
                "unforeseeable", "unpredicted", "unforeseeable", "unanticipated", "unpredicted",
                "unannounced", "unheralded", "unplanned", "unsuspected", "out-of-the-blue",
                "out of nowhere", "without warning", "unannounced", "unbidden", "uninvited",
                "unwelcome", "unwanted", "unasked-for", "unlooked-for", "undreamed-of",
                "unpredicted", "unpredicted", "unanticipated", "unsurprising", "unsurprised",
                "predictable", "expected", "anticipated", "looked-for", "foreseen",
                "foretold", "expectedly", "anticipatedly", "expectantly", "predictably",
                "anticipatedly", "inevitable", "unavoidable", "inexorable", "ineluctable",
                "sure", "certain", "inevitably", "unavoidably", "inexorably", "ineluctably",
                "inevitably", "certainly", "surely", "definitely", "positively", "indubitably",
                "without doubt", "without question", "beyond doubt", "without fail",
                "beyond any doubt", "without a shadow of a doubt", "beyond the shadow of a doubt",
                "inconceivably", "inconceivable", "impossibly", "unthinkably", "incomprehensibly",
                "unbelievably", "improbably", "impossible", "unthinkable", "incomprehensible",
                "unbelievable", "far-fetched", "unimaginable", "improbable", "unlikely",
                "far-fetched", "doubtful", "hard to believe", "questionable", "implausible",
                "impossible", "unthinkable", "inconceivable", "unbelievable", "far-fetched",
                "unimaginable", "improbable", "unlikely", "far-fetched", "doubtful",
                "hard to believe", "questionable", "implausible", "inconceivable", "impossible",
                "unimaginable", "unbelievable", "far-fetched", "improbable", "unlikely",
                "far-fetched", "doubtful", "hard to believe", "questionable", "implausible"],
        "disgust": [
                "revulsion", "repulsion", "disdain", "abhorrence", "repugnance", "aversion",
                "loathing", "nausea", "odium", "contempt", "disgust", "abomination",
                "sickened", "repelled", "detest", "intolerance", "hatefulness", "displeasure",
                "dislike", "offended", "discomfort", "indignation", "irritation", "anger",
                "enmity", "hostility", "antipathy", "scorn", "irritate", "aggravation",
                "annoyance", "disapprove", "disparagement", "aberration", "disbelief",
                "disparaging", "disregard", "disrespect", "insult", "disinclined", "dismay",
                "hatred", "insulted", "irked", "mortified", "peeved", "pest", "rankled",
                "resentful", "sickened", "turn-off", "turned off", "turnoff", "disgusted", "disgusting", "disgustful", "disgustingly", "disgustedly",
                "disgustfully", "disgustingly", "disgustingness", "disgustfulness",
                "disgustingly", "disgustfulness", "disgustingly", "disgustfully",
                "disgustful", "abhorrent", "loathsome", "nauseating", "vile", "offensive",
                "off-putting", "repellent", "repulsive", "repugnant", "distasteful",
                "unpleasant", "horrible", "awful", "terrible", "abominable", "detestable",
                "unsavory", "gross", "yucky", "icky", "sickening", "nauseous", "nauseated",
                "odoriferous", "malodorous", "stenchful", "foul-smelling", "putrid",
                "vomit-inducing", "disgustful", "revolting", "horrifying", "appalling",
                "shocking", "frightening", "horrifyingly", "appallingly", "shockingly",
                "frighteningly", "horrifically", "appallingly", "shockingly", "frighteningly",
                "horrifically", "abhorrently", "loathsomely", "nauseatingly", "vilely",
                "offensively", "repellently", "repulsively", "repugnantly", "distastefully",
                "unpleasantly", "horribly", "awfully", "terribly", "abominably", "detestably",
                "unsavorily", "grossly", "yuckily", "ickily", "sickeningly", "nauseously",
                "nauseatedly", "odoriferously", "malodorously", "stenchfully", "foul-smellingly",
                "putridly", "vomit-inducingly", "disgustingly", "revoltingly", "horrifyingly",
                "appallingly", "shockingly", "frighteningly", "horrifically", "abhorrently",
                "loathsomely", "nauseatingly", "vilely", "offensively", "repellently",
                "repulsively", "repugnantly", "distastefully", "unpleasantly", "horribly",
                "awfully", "terribly", "abominably", "detestably", "unsavorily", "grossly",
                "yuckily", "ickily", "sickeningly", "nauseously", "nauseatedly", "odoriferously",
                "malodorously", "stenchfully", "foul-smellingly", "putridly", "vomit-inducingly",
                "dissatisfied", "unhappy", "unfulfilled", "frustrated", "displeased",
                "discontented", "unsatisfied", "displeasedly", "discontentedly", "unsatisfactorily",
                "dissatisfyingly", "displeasingly", "discontentedly", "unsatisfiedly",
                "displeasedness", "discontentedness", "unsatisfiedness", "displeasingness",
                "discontentedness", "unsatisfiedness", "displeasingness", "unsatisfiedness",
                "unsatisfiedness", "displeasingness", "unsatisfiedly", "unsatisfactorily",
                "unpleasedly", "unsatisfiedly", "unsatisfiedly", "displeasedness", "discontentedness",
                "unsatisfiedness", "displeasingness", "unsatisfiedness", "displeasingness",
                "unsatisfiedness", "displeasingness", "unpleasedness", "unpleasantness",
                "displeasingness", "unsatisfiedness", "displeasingness", "unpleasedness",
                "unpleasantness", "unsatisfiedness", "unpleasedness", "unpleasantness",
                "displeasedness", "discontentedness", "unsatisfiedness", "displeasingness",
                "unpleasedness", "unpleasantness", "unsatisfiedness", "unpleasedness",
                "unpleasantness", "unpleasedness", "unpleasantness", "displeasedness",
                "discontentedness", "unsatisfiedness", "displeasingness", "unpleasedness",
                "unpleasantness", "unsatisfiedness", "unpleasedness", "unpleasantness",
                "unpleasedness", "unpleasantness", "displeasedness", "discontentedness",
                "unsatisfiedness", "displeasingness", "unpleasedness", "unpleasantness",
                "unsatisfiedness", "unpleasedness", "unpleasantness", "unpleasedness",
                "unpleasantness", "unpleasedness", "unpleasantness", "displeasedness",
                "discontentedness", "unsatisfiedness", "displeasingness", "unpleasedness",
                "unpleasantness", "unsatisfiedness", "unpleasedness", "unpleasantness",
                "unpleasedness", "unpleasantness", "displeasedness", "discontentedness",
                "unsatisfiedness", "displeasingness", "unpleasedness", "unpleasantness",
                "unsatisfiedness", "unpleasedness", "unpleasantness", "unpleasedness",
                "unpleasantness", "unpleasedness", "unpleasantness", "displeasedness",
                "discontentedness", "unsatisfiedness", "displeasingness", "unpleasedness",
                "unpleasantness", "unsatisfiedness", "unpleasedness", "unpleasantness",
                "unpleasedness", "unpleasantness", "displeasedness", "discontentedness",
                "unsatisfiedness", "displeasingness", "unpleasedness", "unpleasantness",
                "unsatisfiedness", "unpleasedness", "unpleasantness", "unpleasedness",
                "unpleasantness", "unpleasedness", "unpleasantness", "displeasedness",
                "discontentedness", "unsatisfiedness", "displeasingness", "unpleasedness",
                "unpleasantness", "unsatisfiedness", "unpleasedness", "unpleasantness",
                "unpleasedness", "unpleasantness", "displeasedness", "discontentedness",
                "unsatisfiedness", "displeasingness", "unpleasedness", "unpleasantness",
                "unsatisfiedness", "unpleasedness"]
    ]

    func preprocessText(_ text: String, stopwords: Set<String>) -> String {
        //splits the text into an array of substrings using whitespace
        //Stored in the token array
        var tokens = text.components(separatedBy: .whitespacesAndNewlines)
        
        //Remove o=punctuation and set to all lower case
        let punctuation = CharacterSet.punctuationCharacters
        tokens = tokens.map { token in
            //processedToken contains words that passed filtration
            let processedToken = token.trimmingCharacters(in: punctuation)
            //Checking to see if the lowercase version of the token is within the stop words
            if !stopwords.contains(processedToken.lowercased()) {
                return processedToken.lowercased()
            } else {
                return ""
            }
        }
        
        //joins all the tokens into a single string with a space seperation
        let processedText = tokens.joined(separator: " ")
        
        return processedText
    }

    func processText(text: String, emotionDictionary: [String: Set<String>]) -> [String:Int]{
        var emotionCount = [String: Int]()
        
        // Split the text into words
        let words = text.components(separatedBy: .whitespacesAndNewlines)
        
        // Loop through each word
        for word in words {
            // Loop through each emotion set in the emotional dictionary
            for (emotion, wordSet) in emotionDictionary {
                // Check if the word is in the current emotion set
                if wordSet.contains(word) {
                    // Increment the count for the emotion
                    emotionCount[emotion, default: 0] += 1
                }
            }
        }
        return emotionCount
    }

    func runProcess(journalContent: String) -> [String:Int]{
        let preprocessedEntry = preprocessText(journalContent, stopwords: stopwords)
        // Count emotions in the text
        let emotionCount = processText(text: preprocessedEntry, emotionDictionary: emotionalDictionary)
        return emotionCount
    }

}
